services:
  backend:
    container_name: backend
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - ./.env
    command: gunicorn backend.config.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:17
    env_file:
      - ./.env
    volumes:
      - ~/.pg/pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
