services:
  backend:
    container_name: backend
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - ./.env.prod
      - ./.env.prod.db
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - database
      - redis

  database:
    container_name: database
    image: postgres:17-alpine
    env_file:
      - ./.env.prod.db
    volumes:
      - ~/.pg/pg_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
#    environment:
#      - REDIS_PASSWORD=pines