services:
  backend:
    container_name: backend
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - ./.env.prod
      - ./.env.prod.db
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:17
    env_file:
      - ./.env.prod.db
#    volumes:
#      - ~/.pg/pg_data:/var/lib/postgresql/data

#  redis:
#    image: redis:latest
#    container_name: redis
#    environment:
#      - REDIS_PASSWORD=pines