services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    depends_on:
      - database


  database:
    image: postgres:17
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass