# Generated by Django 5.0.6 on 2024-09-24 11:59

import services.mixins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('time_close', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Время закрытия')),
                ('status', models.CharField(choices=[('wait', 'Wait'), ('in_process', 'In_process'), ('done', 'Done')], default='wait', max_length=50)),
                ('report', models.TextField(blank=True, verbose_name='Отчет')),
            ],
            bases=(services.mixins.models.SelfValidationMixin, models.Model),
        ),
    ]
