# Generated by Django 5.0.6 on 2024-11-08 11:30

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
        ('users', '0006_remove_user_users_user_id_1cecd0_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(django.db.models.functions.text.Upper('title'), name='title_upper_index'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=django.contrib.postgres.indexes.HashIndex(fields=['title'], name='title_hash_index'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=django.contrib.postgres.indexes.HashIndex(fields=['status'], name='status_hash_index'),
        ),
    ]
