# Generated by Django 5.0.6 on 2024-12-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_title_upper_gin_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='title_upper_index',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='title_gin_index',
        ),
    ]
