# Generated by Django 5.0.6 on 2024-12-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_task_title_upper_index_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='title_upper_gin_index',
        ),
    ]
