# Generated by Django 5.0.6 on 2024-10-02 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_user_worker_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_super_customer',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='is_super_worker',
        ),
        migrations.AddField(
            model_name='customer',
            name='legal',
            field=models.CharField(choices=[('entity', 'Entity'), ('person', 'Person')], default='person', max_length=50),
        ),
        migrations.AddField(
            model_name='worker',
            name='education',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='worker',
            name='speciality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Enter a valid registration number in the format ABC123.', regex='^(\\+)?((\\d{2,3}) ?\\d|\\d)(([ -]?\\d)|( ?(\\d{2,3}) ?)){5,12}\\d$')], verbose_name='Номер телефона'),
        ),
    ]
