# Generated by Django 5.0.6 on 2024-11-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_remove_customer_is_super_customer_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['type'], name='users_user_type_3fc058_idx'),
        ),
    ]
