# Generated by Django 5.0.6 on 2024-11-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_user_users_user_type_3fc058_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_type_3fc058_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id'], name='users_user_id_1cecd0_idx'),
        ),
    ]
