# Generated by Django 5.0.6 on 2024-11-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_users_user_type_3fc058_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_id_1cecd0_idx',
        ),
    ]
